# Generated by Django 5.0.14 on 2026-04-22 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RpmBuild",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("build_number", models.IntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("building", "Building"),
                            ("built", "Built"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        help_text="Version extracted from the SPEC file",
                        max_length=255,
                    ),
                ),
                (
                    "source_commit",
                    models.CharField(
                        blank=True,
                        help_text="Git commit that was built",
                        max_length=255,
                    ),
                ),
                (
                    "rpm_files",
                    models.JSONField(
                        blank=True, default=list, help_text="Filenames of built RPMs"
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("celery_task_id", models.CharField(blank=True, max_length=255)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "RPM Build",
                "verbose_name_plural": "RPM Builds",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="RpmDistribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Mock config name (e.g. rhel-9-x86_64)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Human-readable name (e.g. RHEL 9 (x86_64))",
                        max_length=200,
                    ),
                ),
                (
                    "mock_config",
                    models.CharField(
                        help_text="Config name passed to mock -r", max_length=100
                    ),
                ),
                (
                    "arch",
                    models.CharField(
                        help_text="Architecture (e.g. x86_64)", max_length=50
                    ),
                ),
                (
                    "rhel_version",
                    models.CharField(
                        help_text="RHEL major version (e.g. 9)", max_length=20
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "RPM Distribution",
                "verbose_name_plural": "RPM Distributions",
                "ordering": ["rhel_version", "arch"],
            },
        ),
        migrations.CreateModel(
            name="RpmBuildLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("level", models.CharField(default="info", max_length=20)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "build",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="rpm.rpmbuild",
                    ),
                ),
            ],
            options={
                "verbose_name": "RPM Build Log",
                "verbose_name_plural": "RPM Build Logs",
                "ordering": ["timestamp"],
            },
        ),
        migrations.AddField(
            model_name="rpmbuild",
            name="distribution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="builds",
                to="rpm.rpmdistribution",
            ),
        ),
        migrations.CreateModel(
            name="RpmPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable package name", max_length=255
                    ),
                ),
                (
                    "git_repo_url",
                    models.CharField(
                        help_text="Git repository URL containing the SPEC file and sources",
                        max_length=2000,
                    ),
                ),
                (
                    "git_branch",
                    models.CharField(
                        default="main",
                        help_text="Git branch to build from",
                        max_length=200,
                    ),
                ),
                (
                    "spec_file",
                    models.CharField(
                        help_text="Relative path to the .spec file within the repo (e.g. SPECS/mypackage.spec)",
                        max_length=500,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("idle", "Idle"),
                            ("building", "Building"),
                            ("built", "Built"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="idle",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rpm_packages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "distributions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Distributions to build for",
                        related_name="packages",
                        to="rpm.rpmdistribution",
                    ),
                ),
            ],
            options={
                "verbose_name": "RPM Package",
                "verbose_name_plural": "RPM Packages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="rpmbuild",
            name="package",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="builds",
                to="rpm.rpmpackage",
            ),
        ),
    ]
