# Generated by Django 5.0.14 on 2026-04-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rpm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rpmpackage",
            name="description",
            field=models.TextField(
                blank=True, default="", help_text="Optional notes about this package"
            ),
        ),
    ]
