# Generated by Django 5.0.14 on 2026-04-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rpm", "0002_add_description_to_rpmpackage"),
    ]

    operations = [
        migrations.AddField(
            model_name="rpmpackage",
            name="available_version",
            field=models.CharField(
                blank=True,
                help_text="Version parsed from the spec file in the git repository",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="rpmpackage",
            name="available_version_checked_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the available version was last fetched from the repo",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="rpmpackage",
            name="last_build_version",
            field=models.CharField(
                blank=True,
                help_text="Version from the most recent successful build (cached)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="rpmpackage",
            name="spec_requires",
            field=models.JSONField(
                blank=True,
                help_text="Runtime and build requirements parsed from the spec file",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="rpmpackage",
            name="spec_requires_checked_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the spec requirements were last parsed",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="rpmpackage",
            name="upstream_checked_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the upstream version was last checked",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="rpmpackage",
            name="upstream_url",
            field=models.URLField(
                blank=True,
                help_text="Upstream URL to watch for new version tags (e.g. https://github.com/user/repo)",
            ),
        ),
        migrations.AddField(
            model_name="rpmpackage",
            name="upstream_version",
            field=models.CharField(
                blank=True,
                help_text="Latest upstream version (auto-fetched from tags)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="rpmpackage",
            name="upstream_version_script",
            field=models.TextField(
                blank=True,
                help_text="Optional script to determine the latest upstream version. Include a shebang line (#!/bin/bash or #!/usr/bin/env python3). Print the version to stdout.",
            ),
        ),
    ]
