# Generated by Django 5.0.14 on 2026-04-22 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rpm", "0003_add_version_tracking_to_rpmpackage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SatelliteServer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for this server",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="Satellite/Katello base URL (e.g. https://satellite.example.com)",
                        max_length=2000,
                    ),
                ),
                (
                    "login",
                    models.CharField(
                        help_text="Service account login created on this server",
                        max_length=255,
                    ),
                ),
                (
                    "token_encrypted",
                    models.TextField(
                        help_text="Fernet-encrypted Personal Access Token"
                    ),
                ),
                (
                    "ssl_verify",
                    models.BooleanField(
                        default=True, help_text="Verify the server's SSL certificate"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="satellite_servers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Satellite Server",
                "verbose_name_plural": "Satellite Servers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SatelliteRepository",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organization", models.CharField(max_length=255)),
                ("product", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                (
                    "repository_id",
                    models.IntegerField(help_text="Katello internal repository ID"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repositories",
                        to="rpm.satelliteserver",
                    ),
                ),
            ],
            options={
                "verbose_name": "Satellite Repository",
                "verbose_name_plural": "Satellite Repositories",
                "ordering": ["server", "organization", "product", "name"],
                "unique_together": {("server", "repository_id")},
            },
        ),
        migrations.CreateModel(
            name="RpmPackageDistributionDestination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "distribution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="destinations",
                        to="rpm.rpmdistribution",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="distribution_destinations",
                        to="rpm.rpmpackage",
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="package_destinations",
                        to="rpm.satelliterepository",
                    ),
                ),
            ],
            options={
                "verbose_name": "Package Distribution Destination",
                "verbose_name_plural": "Package Distribution Destinations",
                "unique_together": {("package", "distribution", "repository")},
            },
        ),
    ]
