# Generated by Django 5.0.14 on 2026-04-22 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flatpak", "0045_external_ref_versions"),
        ("rpm", "0004_satellite_destinations"),
    ]

    operations = [
        migrations.AddField(
            model_name="rpmdistribution",
            name="signing_key",
            field=models.ForeignKey(
                blank=True,
                help_text="GPG key used to sign built RPMs and repository metadata for this distribution",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rpm_distributions",
                to="flatpak.gpgkey",
            ),
        ),
    ]
