# Generated by Django 5.0.14 on 2026-04-22 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flatpak", "0045_external_ref_versions"),
        ("rpm", "0005_add_signing_key_to_distribution"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rpmdistribution",
            name="signing_key",
        ),
        migrations.CreateModel(
            name="RpmPackageSigningKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "distribution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="package_signing_keys",
                        to="rpm.rpmdistribution",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signing_keys",
                        to="rpm.rpmpackage",
                    ),
                ),
                (
                    "signing_key",
                    models.ForeignKey(
                        help_text="GPG key used to sign built RPMs and repomd.xml",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rpm_package_signing_keys",
                        to="flatpak.gpgkey",
                    ),
                ),
            ],
            options={
                "verbose_name": "Package Signing Key",
                "verbose_name_plural": "Package Signing Keys",
                "unique_together": {("package", "distribution")},
            },
        ),
    ]
