# Generated by Django 5.0.14 on 2026-04-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rpm", "0010_rpmpackage_allow_internet_access"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rpmrepository",
            name="enabled",
            field=models.BooleanField(
                default=False,
                help_text="Pre-selected by default when configuring a new build for this distribution",
            ),
        ),
    ]
