# Generated by Django 5.0.14 on 2026-07-14 12:46

from django.db import migrations, models


def forwards_map_repo_sources(apps, schema_editor):
    RpmRepository = apps.get_model('rpm', 'RpmRepository')
    for repo in RpmRepository.objects.all():
        source = repo.source
        baseurl = (repo.baseurl or '').lower()
        metalink = (repo.metalink or '').lower()
        mirrorlist = (repo.mirrorlist or '').lower()
        url = ' '.join(v for v in (baseurl, metalink, mirrorlist) if v)

        if '/pulp/' in url or '/katello/' in url:
            new_source = 'satellite'
        elif source == 'epel':
            new_source = 'epel'
        elif source == 'manual':
            new_source = 'third_party'
        else:
            new_source = 'rhsm'

        if repo.source != new_source:
            repo.source = new_source
            repo.save(update_fields=['source'])


def backwards_map_repo_sources(apps, schema_editor):
    RpmRepository = apps.get_model('rpm', 'RpmRepository')
    for repo in RpmRepository.objects.all():
        if repo.source == 'epel':
            new_source = 'epel'
        elif repo.source == 'third_party':
            new_source = 'manual'
        else:
            new_source = 'subscription'

        if repo.source != new_source:
            repo.source = new_source
            repo.save(update_fields=['source'])


class Migration(migrations.Migration):

    dependencies = [
        ("rpm", "0014_rpmpackage_organisations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rpmrepository",
            name="source",
            field=models.CharField(
                choices=[
                    ("rhsm", "RHSM Subscription"),
                    ("satellite", "Satellite / Katello"),
                    ("epel", "EPEL"),
                    ("third_party", "Third Party / Custom"),
                ],
                default="rhsm",
                max_length=50,
            ),
        ),
        migrations.RunPython(forwards_map_repo_sources, backwards_map_repo_sources),
    ]
