# Generated by Django 5.0.14 on 2026-07-28 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rpm", "0018_rpmrepository_ssl_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rpmrepository",
            name="baseurl",
            field=models.TextField(blank=True, help_text="Base URL when available"),
        ),
    ]
