from django.urls import path
from . import views

app_name = 'flatpak'

urlpatterns = [
    path('gpg-keys/', views.GPGKeyListView.as_view(), name='gpgkey_list'),
    path('gpg-keys/generate/', views.gpgkey_generate, name='gpgkey_generate'),
    path('gpg-keys/import/', views.gpgkey_import, name='gpgkey_import'),
    path('gpg-keys/<int:pk>/', views.GPGKeyDetailView.as_view(), name='gpgkey_detail'),
    path('gpg-keys/<int:pk>/delete/', views.GPGKeyDeleteView.as_view(), name='gpgkey_delete'),
    path('gpg-keys/<int:pk>/download/', views.GPGKeyDownloadView.as_view(), name='gpgkey_download'),
    path('repos/', views.RepositoryListView.as_view(), name='repo_list'),
    path('repos/<int:pk>/', views.RepositoryDetailView.as_view(), name='repo_detail'),
    path('repos/create/', views.RepositoryCreateView.as_view(), name='repo_create'),
    path('repos/<int:pk>/edit/', views.RepositoryUpdateView.as_view(), name='repo_edit'),
    path('repos/<int:pk>/delete/', views.RepositoryDeleteView.as_view(), name='repo_delete'),
    path('repos/<int:pk>/update-metadata/', views.RepositoryUpdateMetadataView.as_view(), name='repo_update_metadata'),
    path('repos/<int:repo_pk>/subsets/create/', views.RepositorySubsetCreateView.as_view(), name='subset_create'),
    path('subsets/<int:pk>/edit/', views.RepositorySubsetUpdateView.as_view(), name='subset_edit'),
    path('subsets/<int:pk>/delete/', views.RepositorySubsetDeleteView.as_view(), name='subset_delete'),
    path('packages/', views.PackageListView.as_view(), name='package_list'),
    path('packages/create/', views.PackageCreateView.as_view(), name='package_create'),
    path('packages/<int:pk>/', views.PackageDetailView.as_view(), name='package_detail'),
    path('packages/<int:pk>/edit/', views.PackageUpdateView.as_view(), name='package_edit'),
    path('packages/<int:pk>/delete/', views.PackageDeleteView.as_view(), name='package_delete'),
    path('packages/<int:pk>/retry/', views.PackageRetryView.as_view(), name='package_retry'),
    path('packages/<int:pk>/builds/', views.PackageBuildsApiView.as_view(), name='package_builds_api'),
    path('packages/<int:pk>/check-upstream/', views.PackageCheckUpstreamView.as_view(), name='package_check_upstream'),
    path('packages/<int:pk>/commit/', views.PackageCommitView.as_view(), name='package_commit'),
    path('packages/<int:pk>/publish/', views.PackagePublishView.as_view(), name='package_publish'),
    path('builds/', views.BuildListView.as_view(), name='build_list'),
    path('builds/<int:pk>/', views.BuildDetailView.as_view(), name='build_detail'),
    path('builds/<int:build_pk>/promote/', views.PromoteView.as_view(), name='promote'),
    path('builds/<int:pk>/promotions/', views.BuildPromotionsApiView.as_view(), name='build_promotions_api'),
    path('promotions/', views.PromotionListView.as_view(), name='promotion_list'),
    path('promotions/<int:pk>/delete/', views.PromotionDeleteView.as_view(), name='promotion_delete'),
    path('config/', views.ConfigView.as_view(), name='config'),
    path('config/run-cleanup/', views.RunCleanupNowView.as_view(), name='run_cleanup'),
    path('dependencies/', views.dependencies_list, name='dependencies_list'),
    path('repositories/<path:repo_path>', views.serve_repository, name='serve_repository'),
]
