# Generated by Django 5.0.14 on 2026-07-10 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flatpak", "0052_alter_package_upstream_unstable_version_and_more"),
        ("users", "0004_user_email_not_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ldapsource",
            name="bind_dn",
            field=models.CharField(
                help_text="Service account DN (e.g. CN=svc,DC=example,DC=com)",
                max_length=512,
            ),
        ),
        migrations.AlterField(
            model_name="ldapsource",
            name="group_base_dn",
            field=models.CharField(
                blank=True,
                help_text="Group search base DN (leave blank to use base_dn)",
                max_length=512,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="userrole",
            name="organisation",
            field=models.ForeignKey(
                blank=True,
                help_text="Leave blank for a global role. Set to restrict to a specific organisation.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_roles",
                to="flatpak.organisation",
            ),
        ),
    ]
