# Generated by Django 5.0.14 on 2026-08-13 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flatpak", "0053_client_bios_version"),
        ("users", "0005_alter_ldapsource_bind_dn_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PermissionGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resource",
                    models.CharField(
                        choices=[
                            ("repositories", "Repositories"),
                            ("gpg_keys", "GPG Keys"),
                            ("flatpaks", "Flatpaks"),
                            ("rpms", "RPMs"),
                            ("builds", "Builds"),
                            ("clients", "Clients"),
                            ("users", "Users"),
                            ("config", "Config"),
                            ("api", "API"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("read", "Read"),
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("build", "Build"),
                            ("publish", "Publish"),
                            ("sync", "Sync"),
                            ("manage_users", "Manage Users"),
                            ("admin", "Admin"),
                        ],
                        max_length=20,
                    ),
                ),
                ("granted", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank for a global permission. Set to restrict to a specific organisation.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permission_grants",
                        to="flatpak.organisation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permission_grants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Permission Grant",
                "verbose_name_plural": "Permission Grants",
                "ordering": ["user", "resource", "action"],
                "unique_together": {("user", "organisation", "resource", "action")},
            },
        ),
    ]
