# Generated by Django 5.0.14 on 2026-08-13 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flatpak", "0053_client_bios_version"),
        ("users", "0006_permissiongrant"),
    ]

    operations = [
        migrations.CreateModel(
            name="PermissionGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the permission group", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description for the group"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank for a global group. Set to restrict the group to a specific organisation.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permission_groups",
                        to="flatpak.organisation",
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="permission_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Permission Group",
                "verbose_name_plural": "Permission Groups",
                "ordering": ["organisation__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="PermissionGroupPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resource",
                    models.CharField(
                        choices=[
                            ("repositories", "Repositories"),
                            ("gpg_keys", "GPG Keys"),
                            ("flatpaks", "Flatpaks"),
                            ("rpms", "RPMs"),
                            ("builds", "Builds"),
                            ("clients", "Clients"),
                            ("users", "Users"),
                            ("config", "Config"),
                            ("api", "API"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("read", "Read"),
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("build", "Build"),
                            ("publish", "Publish"),
                            ("sync", "Sync"),
                            ("manage_users", "Manage Users"),
                            ("admin", "Admin"),
                        ],
                        max_length=20,
                    ),
                ),
                ("granted", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="users.permissiongroup",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank for a global permission. Set to restrict to a specific organisation.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_permission_grants",
                        to="flatpak.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Permission Group Permission",
                "verbose_name_plural": "Permission Group Permissions",
                "ordering": ["group", "resource", "action"],
                "unique_together": {("group", "organisation", "resource", "action")},
            },
        ),
    ]
