# Generated by Django 5.0.14 on 2026-08-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_permissiongroup_permissiongrouppermission"),
    ]

    operations = [
        migrations.AddField(
            model_name="permissiongroup",
            name="is_predefined",
            field=models.BooleanField(
                default=False, help_text="System-managed predefined group"
            ),
        ),
    ]
