# Generated by Django 5.0.14 on 2026-08-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_permissiongroup_legacy_role_mapping"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.AlterField(
            model_name="permissiongrant",
            name="action",
            field=models.CharField(
                choices=[
                    ("read", "Read"),
                    ("create", "Create"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                    ("build", "Build"),
                    ("publish", "Publish"),
                    ("sync", "Sync"),
                    ("manage_users", "Manage Users"),
                    ("admin", "Admin"),
                    ("all", "All"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="permissiongrant",
            name="resource",
            field=models.CharField(
                choices=[
                    ("repositories", "Repositories"),
                    ("gpg_keys", "GPG Keys"),
                    ("flatpaks", "Flatpaks"),
                    ("rpms", "RPMs"),
                    ("builds", "Builds"),
                    ("buildstreams", "Build Streams"),
                    ("externals", "Externals"),
                    ("dependencies", "Dependencies"),
                    ("clients", "Clients"),
                    ("users", "Users"),
                    ("config", "Config"),
                    ("api", "API"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="permissiongrouppermission",
            name="action",
            field=models.CharField(
                choices=[
                    ("read", "Read"),
                    ("create", "Create"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                    ("build", "Build"),
                    ("publish", "Publish"),
                    ("sync", "Sync"),
                    ("manage_users", "Manage Users"),
                    ("admin", "Admin"),
                    ("all", "All"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="permissiongrouppermission",
            name="resource",
            field=models.CharField(
                choices=[
                    ("repositories", "Repositories"),
                    ("gpg_keys", "GPG Keys"),
                    ("flatpaks", "Flatpaks"),
                    ("rpms", "RPMs"),
                    ("builds", "Builds"),
                    ("buildstreams", "Build Streams"),
                    ("externals", "Externals"),
                    ("dependencies", "Dependencies"),
                    ("clients", "Clients"),
                    ("users", "Users"),
                    ("config", "Config"),
                    ("api", "API"),
                ],
                max_length=50,
            ),
        ),
    ]
