# Generated by Django 5.0.14 on 2026-09-20 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_alter_user_managers_alter_permissiongrant_action_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permissiongrant",
            name="action",
            field=models.CharField(
                choices=[
                    ("read", "Read"),
                    ("create", "Create"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                    ("build", "Build"),
                    ("commit", "Commit"),
                    ("promote", "Promote"),
                    ("publish", "Publish"),
                    ("sync", "Sync"),
                    ("manage_users", "Manage Users"),
                    ("admin", "Admin"),
                    ("all", "All"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="permissiongrouppermission",
            name="action",
            field=models.CharField(
                choices=[
                    ("read", "Read"),
                    ("create", "Create"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                    ("build", "Build"),
                    ("commit", "Commit"),
                    ("promote", "Promote"),
                    ("publish", "Publish"),
                    ("sync", "Sync"),
                    ("manage_users", "Manage Users"),
                    ("admin", "Admin"),
                    ("all", "All"),
                ],
                max_length=20,
            ),
        ),
    ]
