# Generated by Django 5.0.14 on 2026-09-20 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flatpak", "0058_client_lockdown"),
        ("users", "0012_alter_permissiongrant_action_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="default_organisation",
            field=models.ForeignKey(
                blank=True,
                help_text="Organisation automatically assigned to newly created items.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_users",
                to="flatpak.organisation",
            ),
        ),
    ]
