# Generated by Django 5.0.14 on 2026-02-18 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Build",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "build_number",
                    models.IntegerField(help_text="Build attempt number (1, 2, 3...)"),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        help_text="Detected application version",
                        max_length=100,
                    ),
                ),
                (
                    "source_commit",
                    models.CharField(
                        blank=True,
                        help_text="Git commit hash that was built",
                        max_length=64,
                    ),
                ),
                (
                    "commit_hash",
                    models.CharField(
                        blank=True, help_text="OSTree commit hash", max_length=64
                    ),
                ),
                (
                    "dependencies",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Flatpak SDK/runtime dependencies",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("building", "Building"),
                            ("built", "Built"),
                            ("committing", "Committing"),
                            ("committed", "Committed"),
                            ("publishing", "Publishing"),
                            ("published", "Published"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="building",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-build_number"],
            },
        ),
        migrations.CreateModel(
            name="BuildArtifact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("file_path", models.CharField(max_length=512)),
                ("file_size", models.BigIntegerField()),
                ("checksum", models.CharField(max_length=64)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "build",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifacts",
                        to="flatpak.build",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GPGKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Key name/description", max_length=255),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email associated with the key", max_length=254
                    ),
                ),
                (
                    "key_id",
                    models.CharField(
                        help_text="GPG key ID", max_length=16, unique=True
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        help_text="GPG key fingerprint", max_length=40, unique=True
                    ),
                ),
                (
                    "public_key",
                    models.TextField(help_text="Public key (ASCII armored)"),
                ),
                (
                    "private_key",
                    models.TextField(
                        help_text="Private key (ASCII armored, encrypted)"
                    ),
                ),
                (
                    "passphrase_hint",
                    models.CharField(
                        blank=True, help_text="Hint for the passphrase", max_length=255
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gpg_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "GPG Key",
                "verbose_name_plural": "GPG Keys",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "package_id",
                    models.CharField(
                        help_text="Flatpak application ID (e.g., org.example.MyApp)",
                        max_length=255,
                    ),
                ),
                (
                    "package_name",
                    models.CharField(
                        help_text="Human-readable package name (e.g., My Application)",
                        max_length=255,
                    ),
                ),
                (
                    "git_repo_url",
                    models.URLField(
                        blank=True, help_text="Git repository URL to build from"
                    ),
                ),
                (
                    "git_branch",
                    models.CharField(
                        blank=True,
                        default="master",
                        help_text="Git branch to build",
                        max_length=100,
                    ),
                ),
                (
                    "branch",
                    models.CharField(
                        default="stable",
                        help_text="Flatpak branch (stable/beta/etc)",
                        max_length=100,
                    ),
                ),
                ("arch", models.CharField(default="x86_64", max_length=50)),
                (
                    "installation_type",
                    models.CharField(
                        choices=[("system", "System"), ("user", "User")],
                        default="user",
                        help_text="Install dependencies as system or user",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("building", "Building"),
                            ("built", "Built"),
                            ("committing", "Committing"),
                            ("committed", "Committed"),
                            ("publishing", "Publishing"),
                            ("published", "Published"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "build_number",
                    models.IntegerField(
                        default=1,
                        help_text="Next build attempt number (increments on retry)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="packages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="build",
            name="package",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="builds",
                to="flatpak.package",
            ),
        ),
        migrations.CreateModel(
            name="Repository",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "collection_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Collection ID for the repository (e.g., org.example.Repo)",
                        max_length=255,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="repositories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "gpg_key",
                    models.ForeignKey(
                        blank=True,
                        help_text="GPG key for signing",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="repositories",
                        to="flatpak.gpgkey",
                    ),
                ),
                (
                    "parent_repos",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Parent repositories in the lifecycle",
                        related_name="child_repos",
                        to="flatpak.repository",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Repositories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="package",
            name="repository",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="packages",
                to="flatpak.repository",
            ),
        ),
        migrations.CreateModel(
            name="RepositorySubset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Subset name", max_length=255)),
                (
                    "collection_id",
                    models.CharField(
                        help_text="Collection ID for this subset", max_length=255
                    ),
                ),
                (
                    "base_url",
                    models.URLField(blank=True, help_text="Base URL for this subset"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subsets",
                        to="flatpak.repository",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Token",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("token", models.CharField(max_length=64, unique=True)),
                (
                    "token_type",
                    models.CharField(
                        choices=[
                            ("upload", "Upload"),
                            ("download", "Download"),
                            ("admin", "Admin"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens",
                        to="flatpak.repository",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BuildLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("level", models.CharField(default="info", max_length=20)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "build",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="flatpak.build",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
                "indexes": [
                    models.Index(
                        fields=["build", "timestamp"],
                        name="flatpak_bui_build_i_92c7ad_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="build",
            index=models.Index(
                fields=["package", "-build_number"],
                name="flatpak_bui_package_aa1e2b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="build",
            index=models.Index(fields=["status"], name="flatpak_bui_status_e20b74_idx"),
        ),
        migrations.AddIndex(
            model_name="build",
            index=models.Index(
                fields=["-started_at"], name="flatpak_bui_started_5ee427_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="build",
            unique_together={("package", "build_number")},
        ),
        migrations.AlterUniqueTogether(
            name="package",
            unique_together={("repository", "package_id", "arch", "branch")},
        ),
        migrations.AlterUniqueTogether(
            name="repositorysubset",
            unique_together={("repository", "name")},
        ),
    ]
