# Generated by Django 5.0.14 on 2026-02-18 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flatpak", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="commit_hash",
            field=models.CharField(
                blank=True, help_text="OSTree commit hash", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="dependencies",
            field=models.JSONField(
                blank=True, help_text="Detected Flatpak dependencies", null=True
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="error_message",
            field=models.TextField(
                blank=True, help_text="Error message if build failed"
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="source_commit",
            field=models.CharField(
                blank=True, help_text="Git commit hash that was built", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="version",
            field=models.CharField(
                blank=True,
                help_text="Version number (extracted from manifest if git-based)",
                max_length=255,
            ),
        ),
    ]
