# Generated by Django 5.0.14 on 2026-02-16 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flatpak", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GPGKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Key name/description", max_length=255),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email associated with the key", max_length=254
                    ),
                ),
                (
                    "key_id",
                    models.CharField(
                        help_text="GPG key ID", max_length=16, unique=True
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        help_text="GPG key fingerprint", max_length=40, unique=True
                    ),
                ),
                (
                    "public_key",
                    models.TextField(help_text="Public key (ASCII armored)"),
                ),
                (
                    "private_key",
                    models.TextField(
                        help_text="Private key (ASCII armored, encrypted)"
                    ),
                ),
                (
                    "passphrase_hint",
                    models.CharField(
                        blank=True, help_text="Hint for the passphrase", max_length=255
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gpg_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "GPG Key",
                "verbose_name_plural": "GPG Keys",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="repository",
            name="gpg_key",
            field=models.ForeignKey(
                blank=True,
                help_text="GPG key for signing",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="repositories",
                to="flatpak.gpgkey",
            ),
        ),
    ]
