# Generated by Django 5.0.14 on 2026-02-16 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flatpak", "0003_gpgkey_repository_gpg_key"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="repository",
            name="default_branch",
        ),
        migrations.AddField(
            model_name="repository",
            name="collection_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Collection ID for the repository (e.g., org.example.Repo)",
                max_length=255,
            ),
        ),
        migrations.CreateModel(
            name="RepositorySubset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Subset name", max_length=255)),
                (
                    "collection_id",
                    models.CharField(
                        help_text="Collection ID for this subset", max_length=255
                    ),
                ),
                (
                    "base_url",
                    models.URLField(blank=True, help_text="Base URL for this subset"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subsets",
                        to="flatpak.repository",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("repository", "name")},
            },
        ),
    ]
