# Generated by Django 5.0.14 on 2026-02-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flatpak", "0004_remove_repository_default_branch_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="parent_repos",
            field=models.ManyToManyField(
                blank=True,
                help_text="Parent repositories in the lifecycle",
                related_name="child_repos",
                to="flatpak.repository",
            ),
        ),
    ]
