# Generated by Django 5.0.14 on 2026-02-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flatpak", "0005_repository_parent_repos"),
    ]

    operations = [
        migrations.AddField(
            model_name="build",
            name="git_branch",
            field=models.CharField(
                blank=True,
                default="master",
                help_text="Git branch to build",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="build",
            name="git_repo_url",
            field=models.URLField(
                blank=True, help_text="Git repository URL to build from"
            ),
        ),
        migrations.AddField(
            model_name="build",
            name="source_commit",
            field=models.CharField(
                blank=True, help_text="Git commit hash that was built", max_length=64
            ),
        ),
        migrations.AlterField(
            model_name="build",
            name="app_id",
            field=models.CharField(
                help_text="Flatpak application ID (e.g., org.example.MyApp)",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="build",
            name="branch",
            field=models.CharField(
                default="stable",
                help_text="Flatpak branch (stable/beta/etc)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="build",
            name="commit_hash",
            field=models.CharField(
                blank=True, help_text="OSTree commit hash", max_length=64
            ),
        ),
    ]
