# Generated by Django 5.0.14 on 2026-02-16 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flatpak", "0006_build_git_branch_build_git_repo_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="build",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("building", "Building"),
                    ("built", "Built"),
                    ("committing", "Committing"),
                    ("committed", "Committed"),
                    ("publishing", "Publishing"),
                    ("published", "Published"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
