# Generated by Django 5.0.14 on 2026-02-16 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flatpak", "0007_alter_build_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="build",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
