# Generated by Django 5.0.14 on 2026-02-17 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flatpak", "0008_build_published_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="build",
            name="dependencies",
            field=models.JSONField(
                blank=True, default=dict, help_text="Flatpak SDK/runtime dependencies"
            ),
        ),
    ]
