# Generated by Django 5.0.14 on 2026-02-17 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flatpak", "0009_build_dependencies"),
    ]

    operations = [
        migrations.AddField(
            model_name="build",
            name="build_number",
            field=models.IntegerField(
                default=1, help_text="Build attempt number (increments on retry)"
            ),
        ),
    ]
