# Generated by Django 5.0.14 on 2026-02-17 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flatpak", "0010_add_build_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="build",
            name="version",
            field=models.CharField(
                blank=True, help_text="Application version", max_length=100
            ),
        ),
    ]
