# Generated by Django 5.0.14 on 2026-03-11 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flatpak", "0010_flatpakremote"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flatpakremote",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
