# Generated by Django 5.0.14 on 2026-02-17 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flatpak", "0011_add_version_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="build",
            name="installation_type",
            field=models.CharField(
                choices=[("system", "System"), ("user", "User")],
                default="system",
                help_text="Install dependencies as system or user",
                max_length=10,
            ),
        ),
    ]
