# Generated by Django 5.0.14 on 2026-03-12 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flatpak", "0011_alter_flatpakremote_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="build_timeout_minutes",
            field=models.PositiveIntegerField(
                default=120,
                help_text="Maximum time (in minutes) allowed for a single flatpak-builder run. Increase for large packages.",
            ),
        ),
    ]
