# Generated by Django 5.0.14 on 2026-03-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flatpak", "0012_siteconfig_build_timeout_minutes"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="stale_build_check_interval_seconds",
            field=models.PositiveIntegerField(
                default=30,
                help_text="How often (in seconds) to check for stuck builds. Set to 0 to disable. Default: 30.",
            ),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="stale_build_timeout_minutes",
            field=models.PositiveIntegerField(
                default=30,
                help_text="Minutes of log inactivity before an in-progress build is considered stuck and marked as failed.",
            ),
        ),
    ]
