# Generated by Django 5.0.14 on 2026-03-18 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flatpak", "0018_siteconfig_promotion_stale_timeout"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="available_version",
            field=models.CharField(
                blank=True,
                help_text="Version detected from manifest/repo without a full build (auto-refreshed)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="available_version_checked_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the available version was last scanned",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="available_version_check_interval_hours",
            field=models.PositiveIntegerField(
                default=6,
                help_text="How often (in hours) to scan git repos for an available version. Set to 0 to disable.",
            ),
        ),
    ]
