# Generated by Django 5.0.14 on 2026-03-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flatpak", "0019_package_available_version_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hostname",
                    models.CharField(
                        help_text="Hostname of the client machine.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "last_checkin",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of the most recent check-in from this client.",
                        null=True,
                    ),
                ),
                (
                    "remotes",
                    models.JSONField(
                        default=list,
                        help_text="All flatpak remotes on the client: [{name, url}, ...].",
                    ),
                ),
                (
                    "managed_remotes",
                    models.JSONField(
                        default=list,
                        help_text="Names of remotes that point to this server.",
                    ),
                ),
                ("installed_count", models.IntegerField(default=0)),
                (
                    "foreign_count",
                    models.IntegerField(
                        default=0,
                        help_text="Flatpaks installed from remotes NOT managed by this server.",
                    ),
                ),
                (
                    "outdated_count",
                    models.IntegerField(
                        default=0,
                        help_text="Flatpaks that have an update available (any remote).",
                    ),
                ),
                (
                    "installed_flatpaks",
                    models.JSONField(
                        default=list,
                        help_text="All installed flatpaks: [{app_id, version, origin}, ...].",
                    ),
                ),
                (
                    "foreign_flatpaks",
                    models.JSONField(
                        default=list,
                        help_text="Flatpaks from non-managed remotes: [{app_id, version, origin}, ...].",
                    ),
                ),
                (
                    "outdated_flatpaks",
                    models.JSONField(
                        default=list,
                        help_text="Flatpaks with available updates: [{app_id, current_version, new_version, origin}, ...].",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
                "ordering": ["hostname"],
            },
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="client_stale_hours",
            field=models.PositiveIntegerField(
                default=24,
                help_text="Hours without a client check-in before the client is shown as stale/red.",
            ),
        ),
    ]
