# Generated by Django 5.0.14 on 2026-03-26 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flatpak", "0020_client_and_stale_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="user_flatpaks",
            field=models.JSONField(
                default=list,
                help_text="Per-user installed flatpaks: [{username, installed: [...], updates_available: [...]}].",
            ),
        ),
    ]
