# Generated by Django 5.0.14 on 2026-03-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flatpak", "0023_buildstreamsource_build_nullable_package"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buildstreamsource",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
