# Generated by Django 5.0.14 on 2026-03-26 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flatpak", "0026_siteconfig_bst_checkout_timeout"),
    ]

    operations = [
        migrations.AddField(
            model_name="buildstreamsource",
            name="produced_refs",
            field=models.TextField(blank=True, default=""),
        ),
    ]
