# Generated by Django 5.0.14 on 2026-03-26 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flatpak", "0030_package_produced_refs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteconfig",
            name="bst1_venv_path",
            field=models.CharField(
                blank=True,
                default="/opt/flat-manager/bst1-venv",
                help_text="Path to the virtualenv root that has BuildStream 1 installed (e.g. /opt/flat-manager/bst1-venv). Must be created with Python 3.11 or earlier — BST 1 is incompatible with Python 3.12+. Leave empty to fall back to the value in settings.py.",
                max_length=500,
            ),
        ),
    ]
