# Generated by Django 5.0.14 on 2026-03-26 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flatpak", "0031_alter_siteconfig_bst1_venv_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="manifest_file",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Relative path to manifest file inside the repo (e.g. subdir/org.example.App.json). Leave blank for auto-detection.",
                max_length=500,
            ),
        ),
    ]
