# Generated by Django 5.0.14 on 2026-03-27 00:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flatpak", "0032_package_manifest_file"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalRef",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ref",
                    models.CharField(
                        help_text="Full OSTree ref (e.g. runtime/org.kde.Platform/x86_64/5.15)",
                        max_length=500,
                    ),
                ),
                ("display_name", models.CharField(blank=True, max_length=255)),
                ("commit_hash", models.CharField(blank=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("pulling", "Pulling"),
                            ("pulled", "Pulled"),
                            ("publishing", "Publishing"),
                            ("published", "Published"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                (
                    "log",
                    models.TextField(blank=True, help_text="Pull/publish log output"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_pulled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="external_refs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "remote",
                    models.ForeignKey(
                        blank=True,
                        help_text="The flatpak remote this ref originates from",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="external_refs",
                        to="flatpak.flatpakremote",
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        help_text="Target parent repository to publish the ref into",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_refs",
                        to="flatpak.repository",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("repository", "ref")},
            },
        ),
    ]
