# Generated by Django 5.0.14 on 2026-03-27 01:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flatpak", "0033_externalref"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalRefPromotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("promoting", "Promoting"),
                            ("promoted", "Promoted"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "external_ref",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotions",
                        to="flatpak.externalref",
                    ),
                ),
                (
                    "promoted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="external_ref_promotions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_repo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_ref_promotions",
                        to="flatpak.repository",
                    ),
                ),
            ],
            options={
                "verbose_name": "External Ref Promotion",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="externalrefpromotion",
            constraint=models.UniqueConstraint(
                fields=("external_ref", "target_repo"),
                name="unique_external_ref_target_repo",
            ),
        ),
    ]
