# Generated by Django 5.0.14 on 2026-03-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flatpak", "0034_external_ref_promotion"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Organisation name", max_length=255, unique=True
                    ),
                ),
                (
                    "responsible_name",
                    models.CharField(
                        help_text="Name of the responsible person", max_length=255
                    ),
                ),
                (
                    "responsible_email",
                    models.EmailField(
                        help_text="Email of the responsible person", max_length=254
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Optional description"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Organisation",
                "verbose_name_plural": "Organisations",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="buildstreamsource",
            name="organisations",
            field=models.ManyToManyField(
                blank=True,
                help_text="Organisations responsible for this BuildStream source",
                related_name="bst_sources",
                to="flatpak.organisation",
            ),
        ),
        migrations.AddField(
            model_name="externalref",
            name="organisations",
            field=models.ManyToManyField(
                blank=True,
                help_text="Organisations responsible for this external ref",
                related_name="external_refs",
                to="flatpak.organisation",
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="organisations",
            field=models.ManyToManyField(
                blank=True,
                help_text="Organisations responsible for this package",
                related_name="packages",
                to="flatpak.organisation",
            ),
        ),
    ]
