# Generated by Django 5.0.14 on 2026-03-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flatpak", "0035_organisation"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="organisations",
            field=models.ManyToManyField(
                blank=True,
                help_text="Organisations this client belongs to.",
                related_name="clients",
                to="flatpak.organisation",
            ),
        ),
    ]
