# Generated by Django 5.0.14 on 2026-03-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flatpak", "0036_client_organisations"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="timezone",
            field=models.CharField(
                blank=True,
                default="",
                help_text="IANA timezone name used for displaying dates and times in the web UI (e.g. Europe/Copenhagen, America/New_York). Leave empty to use the system default (UTC).",
                max_length=100,
            ),
        ),
    ]
