# Generated by Django 5.0.14 on 2026-03-31 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flatpak", "0037_siteconfig_timezone"),
    ]

    operations = [
        migrations.AddField(
            model_name="externalref",
            name="update_available",
            field=models.BooleanField(
                default=False,
                help_text="True when upstream_commit differs from the last pulled commit_hash",
            ),
        ),
        migrations.AddField(
            model_name="externalref",
            name="upstream_checked_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When we last queried the upstream remote for a new commit",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="externalref",
            name="upstream_commit",
            field=models.CharField(
                blank=True,
                help_text="Latest commit hash seen on the upstream remote (populated by periodic check)",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="external_ref_check_interval_hours",
            field=models.PositiveIntegerField(
                default=6,
                help_text="How often (in hours) to check external refs for upstream commit changes. Set to 0 to disable.",
            ),
        ),
    ]
