# Generated by Django 5.0.14 on 2026-03-31 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flatpak", "0038_external_ref_upstream_tracking"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="dependency_ref_check_interval_hours",
            field=models.PositiveIntegerField(
                default=6,
                help_text="How often (in hours) to re-evaluate which packages need a rebuild due to updated dependency refs. Set to 0 to disable.",
            ),
        ),
    ]
