# Generated by Django 5.0.14 on 2026-03-31 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flatpak", "0039_siteconfig_dependency_ref_check_interval"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="deps_need_rebuild",
            field=models.BooleanField(
                default=False,
                help_text="True when one or more dependency ExternalRefs have a newer upstream commit than what this package was last built against",
            ),
        ),
        migrations.CreateModel(
            name="BuildExternalRef",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ref",
                    models.CharField(
                        help_text="Full OSTree ref string (e.g. runtime/org.kde.Platform/x86_64/6.8)",
                        max_length=500,
                    ),
                ),
                (
                    "upstream_commit_at_build",
                    models.CharField(
                        blank=True,
                        help_text="upstream_commit value at the time this build completed",
                        max_length=64,
                    ),
                ),
                (
                    "build",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_ref_snapshots",
                        to="flatpak.build",
                    ),
                ),
                (
                    "external_ref",
                    models.ForeignKey(
                        blank=True,
                        help_text="The ExternalRef used as a dependency in this build",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="build_snapshots",
                        to="flatpak.externalref",
                    ),
                ),
            ],
            options={
                "ordering": ["ref"],
                "unique_together": {("build", "ref")},
            },
        ),
    ]
