# Generated by Django 5.0.14 on 2026-04-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flatpak", "0040_build_external_ref_snapshot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="user_flatpaks",
            field=models.JSONField(
                default=list,
                help_text="Per-user installed flatpaks: [{username, installed: [...]}].",
            ),
        ),
    ]
