# Generated by Django 5.0.14 on 2026-04-10 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flatpak", "0041_alter_client_user_flatpaks"),
    ]

    operations = [
        migrations.AddField(
            model_name="gpgkey",
            name="expires_at",
            field=models.DateField(
                blank=True,
                help_text="Key expiry date (null = never expires)",
                null=True,
            ),
        ),
    ]
