# Generated by Django 5.0.14 on 2026-04-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flatpak", "0042_gpgkey_expires_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="serial_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Hardware serial number reported by the client machine.",
                max_length=255,
            ),
        ),
    ]
