# Generated by Django 5.0.14 on 2026-04-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flatpak", "0043_client_serial_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="machine_type",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Hardware model/type reported by the client machine.",
                max_length=255,
            ),
        ),
    ]
