# Generated by Django 5.0.14 on 2026-07-10 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flatpak", "0051_externalref_dependencies"),
    ]

    operations = [
        migrations.AlterField(
            model_name="package",
            name="upstream_unstable_version",
            field=models.CharField(
                blank=True,
                help_text="Latest unstable upstream version per version_scheme (only set when newer than the stable upstream version; auto-populated)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="package",
            name="upstream_version_script",
            field=models.TextField(
                blank=True,
                help_text="Optional script to determine the latest upstream version. Include a shebang line (#!/bin/bash or #!/usr/bin/env python3). Print the version on the first line of stdout. Optionally print the release date on the second line (any format, e.g. 2025-03-14). If the date is omitted, the date when this version was first detected is used. Falls back to git tag detection if empty or if the script fails.",
            ),
        ),
    ]
