# Generated by Django 5.0.14 on 2026-08-25 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flatpak", "0054_apppickselection_moderationrequest_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary", models.CharField(blank=True, max_length=500)),
                ("description", models.TextField(blank=True)),
                ("homepage", models.URLField(blank=True)),
                ("icon_url", models.URLField(blank=True)),
                ("screenshots", models.JSONField(blank=True, default=list)),
                ("developer_name", models.CharField(blank=True, max_length=255)),
                ("categories", models.JSONField(blank=True, default=list)),
                ("keywords", models.JSONField(blank=True, default=list)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_mobile", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "package",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="app_metadata",
                        to="flatpak.package",
                    ),
                ),
            ],
        ),
    ]
