# Generated by Django 5.0.14 on 2026-08-25 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flatpak", "0055_appmetadata"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppUsageObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_id", models.CharField(db_index=True, max_length=255)),
                ("version", models.CharField(blank=True, max_length=255)),
                ("branch", models.CharField(blank=True, max_length=100)),
                ("origin", models.CharField(blank=True, max_length=500)),
                ("commit", models.CharField(blank=True, max_length=255)),
                ("observed_at", models.DateTimeField(db_index=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="app_usage_observations",
                        to="flatpak.client",
                    ),
                ),
            ],
            options={
                "ordering": ["-observed_at"],
                "indexes": [
                    models.Index(
                        fields=["app_id", "-observed_at"],
                        name="flatpak_app_app_id_86a18c_idx",
                    ),
                    models.Index(
                        fields=["client", "-observed_at"],
                        name="flatpak_app_client__8cded4_idx",
                    ),
                ],
            },
        ),
    ]
