# Generated by Django 5.0.14 on 2026-09-02 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flatpak", "0057_apppicktheme_apppickselection_theme_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="lockdown",
            field=models.BooleanField(
                default=False,
                help_text="When enabled, the client is instructed to disable network access on next check-in.",
            ),
        ),
    ]
