# Generated by Django 5.0.14 on 2026-09-28 11:52

import apps.flatpak.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flatpak", "0058_client_lockdown"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.CharField(
                default=apps.flatpak.models.generate_repository_token,
                max_length=64,
                unique=True,
            ),
        ),
    ]
